apiVersion: apps/v1
kind: Deployment
metadata:
  name: picketball-racketplanner-backend
  labels:
    app: picketball-racketplanner-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: picketball-racketplanner-backend
  template:
    metadata:
      labels:
        app: picketball-racketplanner-backend
    spec:
      containers:
      - name: picketball-racketplanner-backend
        image: xesuspb/picketballplanner-backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: TZ
          value: "Europe/Madrid"
---
apiVersion: v1
kind: Service
metadata:
  name: picketball-racketplanner-backend-service
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: picketball-racketplanner-backend