apiVersion: apps/v1
kind: Deployment
metadata:
  name: picketball-racketplanner-frontend
  labels:
    app: picketball-racketplanner-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: picketball-racketplanner-frontend
  template:
    metadata:
      labels:
        app: picketball-racketplanner-frontend
    spec:
      containers:
      - name: picketball-racketplanner-frontend
        image: xesuspb/picketballplanner-frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: TZ
          value: "Europe/Madrid"
---
apiVersion: v1
kind: Service
metadata:
  name: picketball-racketplanner-frontend-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: picketball-racketplanner-frontend