apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: picketball-racketplanner-cert
  namespace: synergia
spec:
  secretName: picketball-racketplanner-dev-tls
  dnsNames:
    - picketball.racketplanner.com
    - backend.picketball.racketplanner.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer